package com.example.appconsultas.ui.theme

import androidx.compose.ui.graphics.Color

// Paleta para o Tema Claro (Verde e Branco/Cinza)
val light_primary = Color(0xFF006D3A)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFF98F7B3)
val light_secondary = Color(0xFF4F6353)
val light_onSecondary = Color(0xFFFFFFFF)
val light_background = Color(0xFFFBFDF8)
val light_surface = Color(0xFFFBFDF8)
val light_onBackground = Color(0xFF191C19)
val light_onSurface = Color(0xFF191C19)
val light_surfaceVariant = Color(0xFFDDE5DA)
val light_onSurfaceVariant = Color(0xFF414942)
val light_outline = Color(0xFF717972)

// Paleta para o Tema Escuro (Verde e Preto/Cinza)
val dark_primary = Color(0xFF7CDA99)
val dark_onPrimary = Color(0xFF00391A)
val dark_primaryContainer = Color(0xFF005229)
val dark_secondary = Color(0xFFB7CCB8)
val dark_onSecondary = Color(0xFF223527)
val dark_background = Color(0xFF191C19)
val dark_surface = Color(0xFF191C19)
val dark_onBackground = Color(0xFFE1E3DE)
val dark_onSurface = Color(0xFFE1E3DE)
val dark_surfaceVariant = Color(0xFF414942)
val dark_onSurfaceVariant = Color(0xFFC1C9BF)
val dark_outline = Color(0xFF8B938B)